APPROX_BDAYS_PER_MONTH = 21
APPROX_BDAYS_PER_YEAR = 252
APPROX_BDAYS_PER_YEAR_CRYPTO = 365

MONTHS_PER_YEAR = 12
WEEKS_PER_YEAR = 52

CRYPTO = 'crypto'
DAILY = 'daily'
WEEKLY = 'weekly'
MONTHLY = 'monthly'
YEARLY = 'yearly'

ANNUALIZATION_FACTORS = {
    CRYPTO: APPROX_BDAYS_PER_YEAR_CRYPTO,
    DAILY: APPROX_BDAYS_PER_YEAR,
    WEEKLY: WEEKS_PER_YEAR,
    MONTHLY: MONTHS_PER_YEAR,
    YEARLY: 1
}
